version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.hibernate:hibernate-validator
    versions:
    - 5.3.6.Final
    - 6.1.5.Final
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.9.8
